### ISSUE TITLE
Our custone jre is not able to download data.

### ISSUE THREAD

**Issue by HydrolienF** [HydrolienF/Formiko#299]
Solve it.
```
ERREUR(Folder.ini l116) An error occured when fixing file.
Correction apportée : Downolad file from main repository
ERREUR(fichier.download l173) Fail to download C:/Users/lili5/AppData/Roaming/Formiko/data/data.zip from https://github.com/HydrolienF/Formiko/releases/download/1.43.9/data.zip.
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:356)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:202)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1600)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at java.base/java.net.URL.openStream(URL.java:1167)
        at fr.formiko.usuel.fichier.download(fichier.java:168)
        at fr.formiko.usuel.Folder.downloadData(Folder.java:245)
        at fr.formiko.usuel.Folder.ini(Folder.java:117)
        at fr.formiko.usuel.Folder.ini(Folder.java:124)
        at fr.formiko.formiko.Main.initialisation(Main.java:277)
        at fr.formiko.formiko.Main.iniLaunch(Main.java:127)
        at fr.formiko.formiko.Main.launch(Main.java:138)
        at fr.formiko.formiko.Main.main(Main.java:107)
```

**Comment by HydrolienF** [comment]
https://stackoverflow.com/questions/9249158/why-do-i-get-a-handshake-failure-java-ssl

**Comment by HydrolienF** [comment]
Maybe we just need to add the 2 security module in our custone jre

**Comment by HydrolienF** [comment]
adding jdk.crypto.ec to the module in jlink solve it.

**Comment by HydrolienF** [comment]
Lets download the new jlink from a separate repository.
