### ISSUE TITLE
exeption with contenu of CCase null.

### ISSUE THREAD

**Issue by HydrolienF** [HydrolienF/Formiko#75]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "fr.formiko.formiko.CCase.getContenu()" because "<local5>" is null
	at fr.formiko.formiko.CCreature.actualiserCaseSN(CCreature.java:236)
	at fr.formiko.formiko.GCreature.actualiserCaseSN(GCreature.java:294)
	at fr.formiko.formiko.Joueur.actualiserCaseSN(Joueur.java:124)
	at fr.formiko.graphisme.CEtiquetteJoueur.getGJoueur(CEtiquetteJoueur.java:54)
	at fr.formiko.graphisme.GEtiquetteJoueur.getGJoueur(GEtiquetteJoueur.java:63)
	at fr.formiko.formiko.Partie.iniJoueurEtIa(Partie.java:163)
	at fr.formiko.formiko.Partie.initialisationElément(Partie.java:126)
	at fr.formiko.formiko.Partie.initialisationElément(Partie.java:145)
	at fr.formiko.formiko.Main.lancementNouvellePartie(Main.java:226)
	at fr.formiko.formiko.Main.attenteDeLancementDePartie(Main.java:205)
	at fr.formiko.formiko.Main.launch(Main.java:184)
	at fr.formiko.formiko.Main.main(Main.java:159)

**Comment by HydrolienF** [comment]
It have been resolved like 2-3 days ago.
